name: Compile Typst Document (Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装 Scoop 包管理器
    - name: Install Scoop
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        irm get.scoop.sh | iex

        # 安装所需字体
        # 添加字体仓库
        scoop bucket add nerd-fonts
        scoop bucket add slug https://github.com/woyxiang/slug
        # Maple Mono (ttf 格式)
        scoop install Maple-Mono
        # Maple Mono NF
        scoop install Maple-Mono-NF
        # Maple Mono NF CN
        scoop install Maple-Mono-NF-CN
        
        # 安装 Fira Math (数学字体)
        scoop install FiraMathOtf
        scoop install nerd-fonts/LXGWNeoXiHei
        
        # 安装 Typst

        scoop install typst


        # 编译文档

        typst compile main.typ

    # 上传产物
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdf
        path: main.pdf

    - name: Deploy PDF to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # 当前目录
        publish_branch: gh-pages
        keep_files: false  # 保留旧文件
        destination_dir: .  # 发布在 gh-pages 根目录
        enable_jekyll: false  # 禁用 Jekyll，防止 .pdf 被忽略